# -*- coding: utf-8 -*-
"""FizzBuzz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b59yfqGtpFU3dUhlm2Q9Cl4PEJ5edF72
"""

#bibliotecas

def fizzBuzz(n):

  fizzbuzz_list = []
  for i in range(1, n+1):
    fizzbuzz_list.append(i)

  print(fizzbuzz_list)

  for j in range(len(fizzbuzz_list)):
    if fizzbuzz_list[j] % 3 == 0 and fizzbuzz_list[j] % 5 == 0:
      fizzbuzz_list[j] = "FizzBuzz"

    elif fizzbuzz_list[j] % 3 == 0:
      fizzbuzz_list[j] = "Fizz"

    elif fizzbuzz_list[j] % 5 == 0:
      fizzbuzz_list[j] = "Buzz"

    else:
      fizzbuzz_list[j] = fizzbuzz_list[j]

  return fizzbuzz_list

fizzBuzz(15)